apiVersion: apps/v1
kind: Deployment
metadata:
  name: roomnest-api
  labels:
    app: roomnest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: roomnest-api
  template:
    metadata:
      labels:
        app: roomnest-api
    spec:
      containers:
        - name: roomnest-api
          image: roomnest-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Container"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: roomnest-api
spec:
  type: NodePort
  selector:
    app: roomnest-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30080
